### ISSUE TITLE
Bug: Error when no previous annotations

### ISSUE THREAD

**Issue by nachomillangarcia** [hjacobs/kube-downscaler#21]
The downscaler fails at adding `ORIGINAL_REPLICAS_ANNOTATION` if there are no other annotations in the deployment/statefulset.

**Comment by hjacobs** [comment]
Can you add more info or a test to reproduce the problem? At least I did not experience this problem (and I'm pretty sure most of my deployments have no annotations by default).

**Comment by nachomillangarcia** [comment]
Yes, as I could test the problem affects only to statefusets. Here is a YAML of a statefulset with no annotations:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```

When the downscaler scales it to 0, it doesn't save the original replicas annotation. It must be a problem with PyKube.
